name: Deploy to Railway

on:
  push:
    branches: ["main"]

jobs:
  deploy-grafana:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Railway CLI
        run: |
          npm i -g @railway/cli

      - name: Deploy Grafana to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          cd grafana
          railway link ${{ secrets.RAILWAY_PROJECT_ID }}
          railway up --service grafana --detach

  deploy-nginx:
    runs-on: ubuntu-latest
    needs: deploy-grafana
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Railway CLI
        run: |
          npm i -g @railway/cli

      - name: Deploy nginx to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          cd nginx
          railway link ${{ secrets.RAILWAY_PROJECT_ID }}
          railway up --service nginx --detach
